In [1]:
from carbon import CarbonSimulatorUI
from carbon.simulators.carbon_simulator import (
    __version__ as uiversion,
    __date__ as uidate,
)
from jupyformat import *
import pandas as pd
import numpy as np

In [2]:
print("[carbon_simulator] version", uiversion, uidate)
jp()

[carbon_simulator] version 1.0-usepos1 21/Nov/2022

# Carbon Simulation - Test 34

In [3]:
Sim = CarbonSimulatorUI(verbose=False, raiseonerror=False, pair="ETHUSDC")
Sim

CarbonSimulatorUI(<0 orders, 0 trades>, pair='ETHUSDC')

In [4]:
Sim.add_order("ETH", 10, 2000, 2000)
Sim.add_order("ETH", 10, 2010, 2010)
Sim.add_order("ETH", 20, 2020, 2020)
Sim.add_order("ETH", 30, 2030, 2030)
Sim.add_order("ETH", 40, 2040, 2040)
Sim.add_strategy("ETH", 10, 2050, 2050, 5000, 1060, 1060)
Sim.add_strategy("ETH", 10, 2070, 2070, 5000, 1080, 1080)
Sim.add_strategy("ETH", 10, 2090, 2090, 5000, 1100, 1100)
Sim

CarbonSimulatorUI(<11 orders, 0 trades>, pair='ETHUSDC')

In [5]:
Sim.state()["orders"]

,id,pair,tkn,y_int,y,y_unit,p_start,p_end,p_marg,p_unit,lid
0,0,ETHUSDC,ETH,10.0,10.0,ETH,2000.0,2000.0,2000.0,USDC per ETH,0
1,1,ETHUSDC,ETH,10.0,10.0,ETH,2010.0,2010.0,2010.0,USDC per ETH,1
2,2,ETHUSDC,ETH,20.0,20.0,ETH,2020.0,2020.0,2020.0,USDC per ETH,2
3,3,ETHUSDC,ETH,30.0,30.0,ETH,2030.0,2030.0,2030.0,USDC per ETH,3
4,4,ETHUSDC,ETH,40.0,40.0,ETH,2040.0,2040.0,2040.0,USDC per ETH,4
5,5,ETHUSDC,ETH,10.0,10.0,ETH,2050.0,2050.0,2050.0,USDC per ETH,6
6,6,ETHUSDC,USDC,5000.0,5000.0,USDC,1060.0,1060.0,1060.0,USDC per ETH,5
7,7,ETHUSDC,ETH,10.0,10.0,ETH,2070.0,2070.0,2070.0,USDC per ETH,8
8,8,ETHUSDC,USDC,5000.0,5000.0,USDC,1080.0,1080.0,1080.0,USDC per ETH,7
9,9,ETHUSDC,ETH,10.0,10.0,ETH,2090.0,2090.0,2090.0,USDC per ETH,10
10,10,ETHUSDC,USDC,5000.0,5000.0,USDC,1100.0,1100.0,1100.0,USDC per ETH,9

In [6]:
help(Sim.amm_sells)

Help on method amm_sells in module carbon.simulators.carbon_simulator:

amm_sells(tkn: str, amt: Any, pair: str = None, execute: bool = True, inpair: bool = True, limit_price: Any = None, use_positions: List[int] = None) -> Dict[str, Any] method of carbon.simulators.carbon_simulator.CarbonSimulatorUI instance
    the AMM sells (and the trader buys) `amt` > 0 of `tkn`

    :tkn:           the token sold by the AMM and bought by the trader, eg "ETH"
    :amt:           the amount sold by the AMM and bought by the trader (must be positive)
    :pair:          the token pair to which the trade corresponds, eg "ETHUSD"
    :execute:       if True (default), the trade is executed; otherwise only routing is shown
    :inpair:        if True, only match within pair; if False (default), route through all available pairs
    :limit_price:   the limit price of the order (this price or better from point of view
                    of the trader, not the AMM!), quoted in convention of the pair
    :use_positions: the positions to use for the trade (default: all positions)

In [7]:
Sim.amm_sells("ETH", 10, execute=False, pair="ETHUSDC")["trades"]

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,0.0,0,0,route #0,False,False,None,10.0,ETH,20000.0,USDC,ETHUSDC,0,1,2000.0,USDC per ETH
0,0,0,A,AMM sells 10ETH buys 20000USDC,True,False,None,10.0,ETH,20000.0,USDC,ETHUSDC,[0],1,2000.0,USDC per ETH

In [8]:
Sim.amm_sells("ETH", 1, execute=False, use_positions=[1])["trades"]

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,1.0,1,0,route #1,False,False,None,1.0,ETH,2010.0,USDC,ETHUSDC,1,1,2010.0,USDC per ETH
0,1,1,A,AMM sells 1ETH buys 2010USDC,True,False,None,1.0,ETH,2010.0,USDC,ETHUSDC,[1],1,2010.0,USDC per ETH

In [9]:
Sim.amm_sells("ETH", 1, execute=False, use_positions=[2])["trades"]

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,2.0,2,0,route #2,False,False,None,1.0,ETH,2020.0,USDC,ETHUSDC,2,1,2020.0,USDC per ETH
0,2,2,A,AMM sells 1ETH buys 2020USDC,True,False,None,1.0,ETH,2020.0,USDC,ETHUSDC,[2],1,2020.0,USDC per ETH

In [10]:
Sim.amm_sells("ETH", 1, execute=False, use_positions=[3,4])["trades"]

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,3.0,3,0,route #3,False,False,None,1.0,ETH,2030.0,USDC,ETHUSDC,3,1,2030.0,USDC per ETH
0,3,3,A,AMM sells 1ETH buys 2030USDC,True,False,None,1.0,ETH,2030.0,USDC,ETHUSDC,[3],1,2030.0,USDC per ETH

In [11]:
Sim.amm_sells("ETH", 1, execute=False, use_positions=[6])

{'success': False,
 'error': 'Insufficient liquidity across all user positions to support this trade.',
 'exception': AssertionError('Insufficient liquidity across all user positions to support this trade.')}

In [12]:
Sim.amm_sells("ETH", 1, execute=False, use_positions=[7])["trades"]

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,4.0,4,0,route #7,False,False,None,1.0,ETH,2070.0,USDC,ETHUSDC,7,1,2070.0,USDC per ETH
0,4,4,A,AMM sells 1ETH buys 2070USDC,True,False,None,1.0,ETH,2070.0,USDC,ETHUSDC,[7],1,2070.0,USDC per ETH