In [9]:
from carbon import CarbonSimulatorUI
from carbon.simulators.carbon_simulator import (
    __version__ as uiversion,
    __date__ as uidate,
)
from jupyformat import *

In [10]:
print("[carbon_simulator] version", uiversion, uidate)
jp()

[carbon_simulator] version 0.9.10.4 12/Nov/2022

# Carbon Simulation - Test 16

## Single positions

In [11]:
Sim = CarbonSimulatorUI(verbose=False, raiseonerror=False)
Sim

CarbonSimulatorUI(<0 positions, 0 trades>, pair='None')

In [12]:
Sim.add_sgl_pos("ETH", 10, 2000, 2000, "ETHUSDC")
Sim.add_sgl_pos("USDC", 10000, 1000, 1000, "ETHUSDC")
Sim.add_sgl_pos("ETH", 10, 2000, 2000, "ETHUSDC")
Sim.add_sgl_pos("USDC", 10000, 1000, 1000, "ETHUSDC")
Sim.add_linked_pos("ETH", 10, 2000, 2000, 10000, 1000, 1000, "ETHUSDC")
Sim.add_linked_pos("ETH", 10, 1/2000, 1/2000, 10000, 1/1000, 1/1000, "USDCETH")
Sim.state()["orders"]

,id,pair,tkn_name,y_int,y,y_unit,p_start,p_end,p_unit,linked_to_id
0,0,ETHUSDC,ETH,10.000000,10.000000,ETH,2000.000000,2000.000000,USDC per ETH,0
1,1,ETHUSDC,USDC,10000.000000,10000.000000,USDC,1000.000000,1000.000000,USDC per ETH,1
2,2,ETHUSDC,ETH,10.000000,10.000000,ETH,2000.000000,2000.000000,USDC per ETH,2
3,3,ETHUSDC,USDC,10000.000000,10000.000000,USDC,1000.000000,1000.000000,USDC per ETH,3
4,4,ETHUSDC,ETH,10.000000,10.000000,ETH,2000.000000,2000.000000,USDC per ETH,5
5,5,ETHUSDC,USDC,10000.000000,10000.000000,USDC,1000.000000,1000.000000,USDC per ETH,4
6,6,USDCETH,ETH,10.000000,10.000000,ETH,0.000500,0.000500,ETH per USDC,7
7,7,USDCETH,USDC,10000.000000,10000.000000,USDC,0.001000,0.001000,ETH per USDC,6

In [13]:
Sim.amm_sells("ETH", 1, "ETHUSDC")["trades"]

,uid,id,sub_id,note,aggr,exec,amt1,tkn1,amt2,tkn2,pair,route_indexes,num_trades,price_avg,p_unit
0,0.0,0,0,route #0,False,True,0.25,ETH,500.0,USDC,ETHUSDC,0,1,2000.0,USDC per ETH
0,0.1,0,1,route #2,False,True,0.25,ETH,500.0,USDC,ETHUSDC,2,1,2000.0,USDC per ETH
0,0.2,0,2,route #4,False,True,0.25,ETH,500.0,USDC,ETHUSDC,4,1,2000.0,USDC per ETH
0,0.3,0,3,route #6,False,True,0.25,ETH,500.0,USDC,ETHUSDC,6,1,2000.0,USDC per ETH
0,0,0,A,AMM sells 1ETH buys 2000USDC,True,True,1.00,ETH,2000.0,USDC,ETHUSDC,"[0, 2, 4, 6]",4,2000.0,USDC per ETH

In [14]:
Sim.amm_sells("USDC", 1000, "ETHUSDC")["trades"]

,uid,id,sub_id,note,aggr,exec,amt1,tkn1,amt2,tkn2,pair,route_indexes,num_trades,price_avg,p_unit
0,1.0,1,0,route #1,False,True,243.902439,USDC,0.243902,ETH,ETHUSDC,1,1,1000.0,USDC per ETH
0,1.1,1,1,route #3,False,True,243.902439,USDC,0.243902,ETH,ETHUSDC,3,1,1000.0,USDC per ETH
0,1.2,1,2,route #5,False,True,256.097561,USDC,0.256098,ETH,ETHUSDC,5,1,1000.0,USDC per ETH
0,1.3,1,3,route #7,False,True,256.097561,USDC,0.256098,ETH,ETHUSDC,7,1,1000.0,USDC per ETH
0,1,1,A,AMM sells 1000USDC buys 1ETH,True,True,1000.000000,USDC,1.000000,ETH,ETHUSDC,"[1, 3, 5, 7]",4,1000.0,USDC per ETH

In [15]:
Sim.state()["trades"]

,uid,id,sub_id,note,aggr,exec,amt1,tkn1,amt2,tkn2,pair,route_indexes,num_trades,price_avg,p_unit
0,0.0,0,0,route #0,False,True,0.250000,ETH,500.000000,USDC,ETHUSDC,0,1,2000.0,USDC per ETH
0,0.1,0,1,route #2,False,True,0.250000,ETH,500.000000,USDC,ETHUSDC,2,1,2000.0,USDC per ETH
0,0.2,0,2,route #4,False,True,0.250000,ETH,500.000000,USDC,ETHUSDC,4,1,2000.0,USDC per ETH
0,0.3,0,3,route #6,False,True,0.250000,ETH,500.000000,USDC,ETHUSDC,6,1,2000.0,USDC per ETH
0,0,0,A,AMM sells 1ETH buys 2000USDC,True,True,1.000000,ETH,2000.000000,USDC,ETHUSDC,"[0, 2, 4, 6]",4,2000.0,USDC per ETH
0,1.0,1,0,route #1,False,True,243.902439,USDC,0.243902,ETH,ETHUSDC,1,1,1000.0,USDC per ETH
0,1.1,1,1,route #3,False,True,243.902439,USDC,0.243902,ETH,ETHUSDC,3,1,1000.0,USDC per ETH
0,1.2,1,2,route #5,False,True,256.097561,USDC,0.256098,ETH,ETHUSDC,5,1,1000.0,USDC per ETH
0,1.3,1,3,route #7,False,True,256.097561,USDC,0.256098,ETH,ETHUSDC,7,1,1000.0,USDC per ETH
0,1,1,A,AMM sells 1000USDC buys 1ETH,True,True,1000.000000,USDC,1.000000,ETH,ETHUSDC,"[1, 3, 5, 7]",4,1000.0,USDC per ETH