In [12]:
from carbon import CarbonSimulatorUI, P, __version__, __date__
print(f"Carbon v{__version__} ({__date__})")
print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(CarbonSimulatorUI))

Carbon v2.0-beta2 (8/Dec/2022)
CarbonSimulatorUI v2.2 (8/Dec/2022)

# Carbon Simulation - Test 34 - UsePositions

NBTEST: NOTEST_DEFAULT = TEST

## use_position

In [13]:
Sim = CarbonSimulatorUI(verbose=False, raiseonerror=False, pair="ETH/USDC")
Sim

CarbonSimulatorUI(<0 orders, 0 trades>, pair='ETH/USDC', mm='exact', xf=True)

In [14]:
for i in range(10):
    Sim.add_order("ETH", 10, 2000+i, 2200)

In [15]:
r = Sim.state()["orders"].query("disabled==False")
assert len(r) == 10
assert sum(r.query("tkn=='ETH'")["y"]) == 100
r

,id,pair,tkn,y_int,y,y_unit,disabled,p_start,p_end,p_marg,p_unit,lid
0,0,ETHUSDC,ETH,10.0,10.0,ETH,False,2000.0,2200.0,2000.0,USDC per ETH,1
2,2,ETHUSDC,ETH,10.0,10.0,ETH,False,2001.0,2200.0,2001.0,USDC per ETH,3
4,4,ETHUSDC,ETH,10.0,10.0,ETH,False,2002.0,2200.0,2002.0,USDC per ETH,5
6,6,ETHUSDC,ETH,10.0,10.0,ETH,False,2003.0,2200.0,2003.0,USDC per ETH,7
8,8,ETHUSDC,ETH,10.0,10.0,ETH,False,2004.0,2200.0,2004.0,USDC per ETH,9
10,10,ETHUSDC,ETH,10.0,10.0,ETH,False,2005.0,2200.0,2005.0,USDC per ETH,11
12,12,ETHUSDC,ETH,10.0,10.0,ETH,False,2006.0,2200.0,2006.0,USDC per ETH,13
14,14,ETHUSDC,ETH,10.0,10.0,ETH,False,2007.0,2200.0,2007.0,USDC per ETH,15
16,16,ETHUSDC,ETH,10.0,10.0,ETH,False,2008.0,2200.0,2008.0,USDC per ETH,17
18,18,ETHUSDC,ETH,10.0,10.0,ETH,False,2009.0,2200.0,2009.0,USDC per ETH,19

In [16]:
help(Sim.amm_sells)

Help on method amm_sells in module carbon.simulators.carbon_simulator:

amm_sells(tkn: str, amt: Any, pair: str = None, execute: bool = True, inpair: bool = True, limit_price: Any = None, threshold_orders: int = 10, use_positions: List[int] = None, use_positions_matchlevel: List[int] = []) -> Dict[str, Any] method of carbon.simulators.carbon_simulator.CarbonSimulatorUI instance
    the AMM sells (and the trader buys) `amt` > 0 of `tkn`

    :tkn:               the token sold by the AMM and bought by the trader, eg "ETH"
    :amt:               the amount sold by the AMM and bought by the trader (must be positive)
    :pair:              the token pair to which the trade corresponds, eg "ETHUSD"
    :execute:           if True (default), the trade is executed; otherwise only routing is shown
    :inpair:            if True, only match within pair; if False (default), route through all available pairs
    :limit_price:       the limit price of the order (this price or better from point of view
                        of the trader, not the AMM!), quoted in convention of the pair
    :threshold_orders:  the maximum number of order to be routed through using the alpha router
    :use_positions: the positions to use for the trade (default: all positions)

In [17]:
r = Sim.amm_sells("ETH", 10, execute=False, pair="ETH/USDC")["trades"]
p = r.iloc[-1]["price"]
print(p)
r

2013.469153

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,0.0,0,0,route #0,False,False,None,1.219233,ETH,2452.380790,USDC,ETHUSDC,0,1,2013.469153,USDC per ETH
0,0.1,0,1,route #2,False,False,None,1.171826,ETH,2357.614182,USDC,ETHUSDC,2,1,2013.469153,USDC per ETH
0,0.2,0,2,route #4,False,False,None,1.123940,ETH,2261.836661,USDC,ETHUSDC,4,1,2013.469153,USDC per ETH
0,0.3,0,3,route #6,False,False,None,1.075568,ETH,2165.032851,USDC,ETHUSDC,6,1,2013.469153,USDC per ETH
0,0.4,0,4,route #8,False,False,None,1.026703,ETH,2067.187066,USDC,ETHUSDC,8,1,2013.469153,USDC per ETH
0,0.5,0,5,route #10,False,False,None,0.977337,ETH,1968.283295,USDC,ETHUSDC,10,1,2013.469153,USDC per ETH
0,0.6,0,6,route #12,False,False,None,0.927462,ETH,1868.305198,USDC,ETHUSDC,12,1,2013.469153,USDC per ETH
0,0.7,0,7,route #14,False,False,None,0.877071,ETH,1767.236098,USDC,ETHUSDC,14,1,2013.469153,USDC per ETH
0,0.8,0,8,route #16,False,False,None,0.826155,ETH,1665.058967,USDC,ETHUSDC,16,1,2013.469153,USDC per ETH
0,0.9,0,9,route #18,False,False,None,0.774706,ETH,1561.756424,USDC,ETHUSDC,18,1,2013.469153,USDC per ETH
0,0,0,A,AMM sells 10ETH buys 20135USDC,True,False,None,10.000000,ETH,20134.691532,USDC,ETHUSDC,"[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]",10,2013.469153,USDC per ETH

In [18]:
r = Sim.amm_sells("ETH", 10, execute=False, use_positions=[2])["trades"]
p1 = r.iloc[-1]["price"]
print(p1, p)
assert p1>p
assert r.iloc[-1]["routeix"] == "[2]"
r

2098.142035 2013.469153

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,1.0,1,0,route #2,False,False,None,10.0,ETH,20981.420352,USDC,ETHUSDC,2,1,2098.142035,USDC per ETH
0,1,1,A,AMM sells 10ETH buys 20981USDC,True,False,None,10.0,ETH,20981.420352,USDC,ETHUSDC,[2],1,2098.142035,USDC per ETH

In [19]:
r = Sim.amm_sells("ETH", 10, execute=False, use_positions=[4])["trades"]
p2 = r.iloc[-1]["price"]
print(p2, p1, p)
assert p2>p1
assert r.iloc[-1]["routeix"] == "[4]"
r

2098.666243 2098.142035 2013.469153

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,2.0,2,0,route #4,False,False,None,10.0,ETH,20986.662431,USDC,ETHUSDC,4,1,2098.666243,USDC per ETH
0,2,2,A,AMM sells 10ETH buys 20987USDC,True,False,None,10.0,ETH,20986.662431,USDC,ETHUSDC,[4],1,2098.666243,USDC per ETH

In [20]:
r = Sim.amm_sells("ETH", 10, execute=False, use_positions=[6,8])["trades"]
p3 = r.iloc[-1]["price"]
print(p3, p2, p1, p)
assert p3>p
assert r.iloc[-1]["routeix"] == "[6, 8]"
r

2050.353795 2098.666243 2098.142035 2013.469153

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,3.0,3,0,route #6,False,False,None,5.013651,ETH,10278.479555,USDC,ETHUSDC,6,1,2050.353795,USDC per ETH
0,3.1,3,1,route #8,False,False,None,4.986349,ETH,10225.058395,USDC,ETHUSDC,8,1,2050.353795,USDC per ETH
0,3,3,A,AMM sells 10ETH buys 20504USDC,True,False,None,10.000000,ETH,20503.537951,USDC,ETHUSDC,"[6, 8]",2,2050.353795,USDC per ETH

In [21]:
r = Sim.amm_sells("ETH", 10, execute=False, use_positions=[12,14])["trades"]
p4 = r.iloc[-1]["price"]
print(p4, p3, p2, p1, p)
assert p4>p3
assert r.iloc[-1]["routeix"] == "[12, 14]"
r

2052.673791 2050.353795 2098.666243 2098.142035 2013.469153

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,4.0,4,0,route #12,False,False,None,5.013847,ETH,10290.513955,USDC,ETHUSDC,12,1,2052.673791,USDC per ETH
0,4.1,4,1,route #14,False,False,None,4.986153,ETH,10236.223959,USDC,ETHUSDC,14,1,2052.673791,USDC per ETH
0,4,4,A,AMM sells 10ETH buys 20527USDC,True,False,None,10.000000,ETH,20526.737914,USDC,ETHUSDC,"[12, 14]",2,2052.673791,USDC per ETH

In [22]:
r.iloc[-1]["routeix"]

'[12, 14]'